# Generated by Django 2.0 on 2017-12-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='test_text',
        ),
    ]
