# Generated by Django 2.0 on 2017-12-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0002_auto_20171217_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeuralNetworkTrainer',
            new_name='ImageClassifier',
        ),
    ]
